# 4.1 NumPy nadrray: 다차원 배열 객체

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[-0.31989695, -1.16547232,  0.27273587],
       [-0.74840381,  0.24382588,  0.71791275]])

In [4]:
data * 10

array([[ -3.19896948, -11.6547232 ,   2.72735867],
       [ -7.48403806,   2.43825884,   7.17912749]])

In [5]:
data + data

array([[-0.6397939 , -2.33094464,  0.54547173],
       [-1.49680761,  0.48765177,  1.4358255 ]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### 4.1.1 ndarry 생성

In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[1.14578269e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 3.92511419e+179]],

       [[1.61997976e-051, 1.03100932e+166],
        [1.57374349e+161, 1.31457135e-047],
        [5.15551171e-062, 1.95248575e+160]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray의 자료형

In [18]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [19]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr = np.array([1, 2, 3, 4, 5])

In [23]:
arr.dtype

dtype('int32')

In [24]:
float_arr = arr.astype(np.float64)

In [25]:
float_arr.dtype

dtype('float64')

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [27]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [28]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [29]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)

In [30]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [31]:
int_array = np.arange(10)

In [32]:
calibers = np.array([.22, .270, .357, .380, .44, .50 ], dtype=np.float64)

In [33]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
empty_uint32 = np.empty(8, dtype='u4')

In [35]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### 4.1.3 배열과 스칼라 간의 연산

In [36]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [37]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [39]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [41]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 4.1.4 색인과 슬라이싱 기초

In [42]:
arr = np.arange(10)

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[5]

5

In [45]:
arr[5:8]

array([5, 6, 7])

In [46]:
arr[5:8] = 12

In [47]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [48]:
arr_slice = arr[5:8]

In [50]:
arr_slice[1] = 12345

In [51]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [52]:
arr_slice[:] = 64

In [53]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [55]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[2]

array([7, 8, 9])

In [57]:
arr2d[0][2]

3

In [58]:
arr2d[0, 2]

3

In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
old_values = arr3d[0].copy()

In [63]:
arr3d[0] = 42

In [64]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
arr3d[0] = old_values

In [67]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[1, 0]

array([7, 8, 9])

#### 슬라이스 색인

In [69]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [70]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [73]:
arr2d[1, :2]

array([4, 5])

In [74]:
arr2d[2, :1]

array([7])

In [76]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [78]:
arr2d[:2, 1:] = 0

In [79]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### 4.1.5 불리언 색인

In [80]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [81]:
data = np.random.randn(7, 4)

In [82]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [83]:
data

array([[-1.39803044, -0.84902754,  0.8155573 , -0.1322445 ],
       [-0.03108445, -0.56943953, -0.41801314, -0.54748575],
       [ 0.72239144,  0.07595944, -0.14602535, -1.25488398],
       [ 0.23018329, -1.00655977, -1.039581  , -0.47085009],
       [ 1.9817284 ,  0.23107547,  0.02773539, -0.59581701],
       [ 0.72578898, -0.63863972,  0.45740848, -0.64101784],
       [ 0.2391008 ,  0.87075714, -1.59772467,  1.03673634]])

In [84]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [85]:
data[names == 'Bob']

array([[-1.39803044, -0.84902754,  0.8155573 , -0.1322445 ],
       [ 0.23018329, -1.00655977, -1.039581  , -0.47085009]])

In [86]:
data[names == 'Bob', 2:]

array([[ 0.8155573 , -0.1322445 ],
       [-1.039581  , -0.47085009]])

In [87]:
data[names == 'Bob', 3]

array([-0.1322445 , -0.47085009])

In [88]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [93]:
data[~(names == 'Bob')]

array([[-0.03108445, -0.56943953, -0.41801314, -0.54748575],
       [ 0.72239144,  0.07595944, -0.14602535, -1.25488398],
       [ 1.9817284 ,  0.23107547,  0.02773539, -0.59581701],
       [ 0.72578898, -0.63863972,  0.45740848, -0.64101784],
       [ 0.2391008 ,  0.87075714, -1.59772467,  1.03673634]])

In [95]:
mask = (names == 'Bob') | (names == 'Will')

In [96]:
mask

array([ True, False,  True,  True,  True, False, False])

In [97]:
data[mask]

array([[-1.39803044, -0.84902754,  0.8155573 , -0.1322445 ],
       [ 0.72239144,  0.07595944, -0.14602535, -1.25488398],
       [ 0.23018329, -1.00655977, -1.039581  , -0.47085009],
       [ 1.9817284 ,  0.23107547,  0.02773539, -0.59581701]])

In [98]:
data[data < 0] = 0

In [99]:
data

array([[0.        , 0.        , 0.8155573 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.72239144, 0.07595944, 0.        , 0.        ],
       [0.23018329, 0.        , 0.        , 0.        ],
       [1.9817284 , 0.23107547, 0.02773539, 0.        ],
       [0.72578898, 0.        , 0.45740848, 0.        ],
       [0.2391008 , 0.87075714, 0.        , 1.03673634]])

In [100]:
data[names != 'Joe'] = 7

In [101]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.72578898, 0.        , 0.45740848, 0.        ],
       [0.2391008 , 0.87075714, 0.        , 1.03673634]])

### 4.1.6 팬시 색인

In [107]:
arr = np.empty((8, 4))

In [108]:
arr

array([[6.95201069e-310, 1.25524786e-310, 1.14578050e-311,
        1.14581631e-311],
       [1.14581631e-311, 1.14577919e-311, 1.14581631e-311,
        8.37157295e-310],
       [1.14578211e-311, 1.14577951e-311, 1.14578211e-311,
        1.14577956e-311],
       [1.14581631e-311, 8.47300436e-310, 1.14577921e-311,
        1.14577951e-311],
       [1.14579133e-311, 1.14581631e-311, 1.14577919e-311,
        8.48021915e-310],
       [1.14577915e-311, 1.14577922e-311, 1.14581631e-311,
        1.14579133e-311],
       [1.14581631e-311, 8.53454226e-310, 1.14577922e-311,
        1.14577925e-311],
       [1.14580869e-311, 1.14577922e-311, 1.14581631e-311,
        8.58886536e-310]])

In [109]:
for i in range(8):
    arr[i] = i

In [110]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [111]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [112]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [113]:
arr = np.arange(32).reshape((8, 4))

In [114]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [115]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [116]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [117]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### 4.1 7 배열 전치와 축 바꾸기

In [120]:
arr = np.arange(15).reshape((3, 5))

In [121]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [123]:
arr = np.random.randn(6, 3)

In [124]:
arr

array([[-0.78769344,  0.24933194, -0.91996192],
       [ 1.0859481 ,  0.58263357, -0.58318773],
       [ 1.03137411,  1.53636035,  0.07597468],
       [ 0.92122603, -0.04783072, -1.01847052],
       [-1.21319459, -1.92647027, -0.01195515],
       [ 0.43041241, -0.93283997,  1.49188822]])

In [125]:
np.dot(arr.T, arr)

array([[ 5.36923013,  3.91248947, -0.11191575],
       [ 3.91248947,  7.34579729, -1.77238368],
       [-0.11191575, -1.77238368,  4.4553656 ]])

In [129]:
arr = np.arange(16).reshape((2, 2, 4))

In [127]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [130]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [131]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [132]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])